### ISSUE TITLE
Parâmetro de dismo.mod() sem efeito

### ISSUE THREAD

**Issue by gmgall** [Model-R/Back-end#4]
Mexendo no código para implementar #3 percebi que o parâmetro `n.back` de `dismo.mod()` não tem qualquer efeito.

Independente do valor passado pelo usuário, `n.back` será sobrescrito com 2 vezes a quantidade de pontos de ocorrência para a espécie em processamento.

No momento em que escrevo essa issue (6a1378eb46f279d21c14d55802df7a15d0a61e0d), isso acontece na [linha 707 de `dismo.mod()`](https://github.com/Model-R/Back-end/blob/master/ENM/fct/modelos.R#L707).

Posso excluir esse parâmetro?

**Comment by AndreaSanchezTapia** [comment]
isso foi devido ao projeto de mata atlântica. A linha estava comentada mas pode ser deletada e o parâmetro não deve ser apagado (só a linha)
