### ISSUE TITLE
Resolver concorrência na escrita de valores "evaluate"

### ISSUE THREAD

**Issue by gmgall** [Model-R/Back-end#5]
Outra que descobri ao tentar implementar #3.

Hoje arquivos com nome no esquema `evaluateNomeDaEspecie_partição.txt` são escritos no final de cada iteração do loop que gera os modelos para cada algoritmo. Em pseudocódigo, hoje temos algo assim dentro de `dismo.mod()`:

```R
for (i in unique(group)){
  # separa ocorrências em teste e treino
  if (algoritmo1) {
    do_algoritmo1()
  }
  if (algoritmo2) {
    do_algoritmo2()
  }
  # >>> escreve evaluateNomeDaEspecie_partição.txt <<<
}
```

Isso funciona bem porque o código referente a cada algoritmo acumula as informações num data frame que **só ao fim de cada iteração** é escrito num arquivo `evaluateNomeDaEspecie_partição.txt`.

Mas, como minha intenção é ter funções isoladas, em determinada execução posso ter o processo fazendo - por exemplo - `do_maxent(especie1)` e o processo fazendo `do_bioclim(especie1)` escrevendo no mesmo arquivo `evaluateespecie1_2.txt` **ao mesmo tempo**. Isso pode acabar truncando o arquivo.

Para implementar #3, precisamos de uma forma melhor de escrever essas informações *evaluate*.

A solução mais simplista seria escrever arquivos `evaluateNomeDaEspecie_partição_ALGORITMO.txt`. Isso não parece que quebra `finalModel()` porque ele lê esses arquivos assim:

```R
evall <- list.files(path = paste0(models.dir, "/", sp), pattern = "evaluate", full.names = T)
```

então ainda funcionaria porque o que é procurado é o padrão `evaluate` nos nomes de arquivo. 

Deixo então minhas perguntas:

1) Esses arquivos são consumidos em mais algum lugar? Se eu fizer essa mudança, quebrarei alguma coisa?
2) Se os arquivos `evaluate*` só são consumidos por `finalModel()`, não seria melhor `finalModel()` receber essas informações por parâmetro ao invés de ter que ler inúmeros arquivos? Provavelmente faremos a execução ficar mais rápida assim.

**Comment by AndreaSanchezTapia** [comment]
1) esse arquivos sao consumidos depois de serem relidos, unificados e reescritos, então dá para fazer a mudança, desde que os novos arquivos possam ser lidos e unificados numa tabela final
2) vou pensar se é melhor. essa tabela final não é tão importante para nós mas para quem não sabe mexer no R e precisa ver o que está acontecendo.

**Comment by gmgall** [comment]
> esse arquivos sao consumidos depois de serem relidos, unificados e reescritos, então dá para fazer a mudança, desde que os novos arquivos possam ser lidos e unificados numa tabela final

Então não quebrarei nada se eu passar a escrever `evaluateNomeDaEspecie_partição_ALGORITMO.txt`, certo?

> vou pensar se é melhor. essa tabela final não é tão importante para nós mas para quem não sabe mexer no R e precisa ver o que está acontecendo.

Escrever ou não os arquivos poderia ser parametrizado também. Assim, podemos gerar os arquivos quando forem necessários e não gerá-los na maioria das outras execuções (meu entendimento é que raramente eles serão necessários, estou errado?).

**Comment by AndreaSanchezTapia** [comment]
> Então não quebrarei nada se eu passar a escrever evaluateNomeDaEspecie_partição_ALGORITMO.txt, certo?
certo

> Escrever ou não os arquivos poderia ser parametrizado também. Assim, podemos gerar os arquivos quando forem necessários e não gerá-los na maioria das outras execuções (meu entendimento é que raramente eles serão necessários, estou errado?).

O evaluate micro que você vai reescrever é usado pelo final.model, mas a tabela grandona -que vem depois de um chamado rbindlist (acho)- é preciso escrever porque é um jeito rápido de conferir o que aconteceu e acho que passará a fazer parte do banco de dados final- pois é a estatística final dos modelos. Não é que seja usada sempre, mas é metadado/resultado que tem que ir junto.

**Comment by FelipeSBarros** [comment]
Pessoal, respondi no slack:
https://model-r.slack.com/archives/C4KK6FZ08/p1491942057646604?thread_ts=1491808962.904287&cid=C4KK6FZ08

confesso que fiquei um pouco perdido com as mensagens e não ví que a discussão era aqui. Abs

**Comment by gmgall** [comment]
Fiquei confuso aqui. A @AndreaSanchezTapia disse

> essa tabela final não é tão importante para nós mas para quem não sabe mexer no R e precisa ver o que está acontecendo

e o @FelipeSBarros disse (na [thread do slack](https://model-r.slack.com/archives/C4KK6FZ08/p1491942057646604?thread_ts=1491808962.904287&cid=C4KK6FZ08))

> A ideia é que esses arquivos não sejam mais escritos em txt mas que sejam enviados ao banco.

Afinal, vamos escrever esses arquivos no disco ou não?

**Comment by FelipeSBarros** [comment]
@gmgall, acredito que a ideia é ter isso no banco. Ao menos estamos contando com isso no modelo do banco de dados. 

Mas a implementação de como isso será feito, pode ser discutida para vermos a melhor forma :
1. Se salvamos direto no banco cada campo assim que o mesmo tenha sido produzido;
2. Se vamos salvar no HD de forma temporária para organismos os dados (caso seja necessario) e só depois disso salvamos no banco. 
3. Alguma outra solução?

**Comment by AndreaSanchezTapia** [comment]
Oi @gmgall , vamos escrever sim. Depois de pensar XD a resposta final foi a mesma que @FelipeSBarros deu, que isso tem que fazer parte do banco. Pelo menos a tabela grandona final que unifica os dados de todas as rodadas de cada espécie.

**Comment by gmgall** [comment]
Ou seja: o que hoje é escrito em arquivos com nome `evaluate*` será escrito no banco.

É isso?

**Comment by FelipeSBarros** [comment]
Sim, @gmgall .
Veja o modelo do banco de dados... Aqui coloco uma parte dele:
![Modelo BD Algoritmo tabela evaluate](https://cloud.githubusercontent.com/assets/7208674/24974136/8f233b4a-1f97-11e7-9c21-7df3af729013.png)
Há uma tabela chamada `evaluate`, relacionada à tabela `experiment` pela tabela auxiliar `experiment_use_algorithm`.

Esse relacionamento foi discutido na reunião em que estavamos todos presentes, pois à época eu tinha colocado a tabela evaluate relacionada direto à tabela `algorithm`.

**Comment by FelipeSBarros** [comment]
Pessoal, adicionei à tabela 'evaluate' do modelo do banco de dados as colunas onde ficarão salvos os dados de 'valuate' ([commit](https://github.com/Model-R/modelo-bd/commit/f2697012965ccf15cf893bffe0d815e997f70303)). 
No R, o nome da linha possuia a informação do nome da espécie, e quando o arquivo era salvo (em ,csv), o nome era salvo também. Como não é o caso do Banco de dados, inclui uma coluna para armazenar o nome da espécie. 

Mas não sei se isso é necessário. @gmgall, Luis Alexandre e @rafaeloliveiralima , vcs acham que o nome pode ser resgatado pelo banco de dados (já que o nome da espécie aparece na tabela "occurrences"?

Segue um print da tabela evaluate:
![Tabela evaluate após commit](https://cloud.githubusercontent.com/assets/7208674/25136764/442fe63a-242c-11e7-85bf-f2ae0633d9d1.png)

**Comment by gmgall** [comment]
Meu SQL/teoria de BD estão bem enferrujados, mas parece-me sim possível obter o nome da espécie de `occurrences`.

Ter `specie` na tabela `evaluate` simplifica a query para obter o nome da espécie a partir de `evaluate` e talvez seja melhor em termos de desempenho. Porém, não sei se essa redundância é boa prática.

Acho que o Luís pode oferecer uma opinião bem mais qualificada que a minha.

-------

Sugestão: abrir uma issue em [modelo-bd](https://github.com/Model-R/modelo-bd) para discutir isso. Continuar aqui parece-me misturar questões de Back-end e de modelo do banco. Minha questão original, a concorrência ao escrever os valores *evalutate*, parece-me resolvida: esses dados irão no banco. Como as tabelas serão organizadas, é uma questão que não concerne mais ao Back-end.

**Comment by gmgall** [comment]
Ao implementar https://github.com/Model-R/Back-end/issues/3, fiz com que os valores _evaluate_ sejam escritos em arquivos com nome no formato `evaluateNomeDaEspecie_particao_algoritmo.txt`.

Isso resolve o problema de concorrência. Não há mais a possibilidade de duas threads distintas tentarem escrever num mesmo arquivo.

Se o conteúdo desses arquivos forem escritos diretamente no banco pelas próprias funções de modelagem, os arquivos `evaluate*` talvez nem precisem ser escritos no disco. Mas isso é uma discussão futura.
