### ISSUE TITLE
Arquivos gerados pela implementação antiga diferem dos gerados pela nova

### ISSUE THREAD

**Issue by gmgall** [Model-R/Back-end#6]
Só percebi isso ao implementar ca8b721ef7b0495ba6450fd1643fa1f07943e72b, mas pode ser um problema mais antigo. Na realidade, nem sei se é um problema. Por isso deixo a questão aqui.

Exemplo de informações escritas nos arquivos `evaluate*` pela implementação antiga (a _tageada_ como [coordenador-IIS](https://github.com/Model-R/Back-end/releases/tag/coordenador-IIS)):

```
"kappa" "spec_sens" "no_omission" "prevalence" "equal_sens_spec" "sensitivity" "AUC" "TSS" "algoritmo" "partition"
"Zygia latifolia (L.) Fawc. & Rendle 1 BioClim" 0.23519412 0.23519412 -1e-04 0.35284118 0.11754706 0.11754706 0.751633986928105 0.444444444444444 "BioClim" 1
```

Exemplo de informações escritas pela implementação mais recente:

```
"kappa" "spec_sens" "no_omission" "prevalence" "equal_sens_spec" "sensitivity" "AUC" "TSS" "algoritmo" "partition"
"Zygia latifolia (L.) Fawc. & Rendle 1 BioClim" 0.23519412 0.11754706 -1e-04 -1e-04 0.11754706 0.11754706 0.744510978043912 0.453759148369927 "BioClim" 1
```

Ambas as execuções foram feitas com o mesmo seed. Não deveriam ser exatamente iguais?

Uma coisa que estranhei é que a implementação antiga sempre escreve a 1ª coluna numérica igual à 2ª. Nesse exemplo `0.23519412`. Isso faz sentido?

Os `*tif` também diferem, mas obviamente não tenho como postar a diferença aqui.

**Comment by FelipeSBarros** [comment]
@gmgall , ótima observação. Ao fazer o teste comentei que aparentemente tudo estava bem e que o "aparemente" se devia ao fato de não conseguir saber se os dados estavam corretos.

A partir do seu alerta comecei olhando o branch `master`. O objeto `evaluate` é criado na [linha 789](https://github.com/Model-R/Back-end/blob/master/ENM/fct/modelos.R#L789) na função `dismo.mod `. Na criação do objeto, são gerados 10 campos (`kappa`, `spec_sens`, `no_omission`, `prevalence`, `equal_sens_spec`, `sensitivity`, `AUC`, `TSS` , `algoritmo`, `partition`).

Percebi que os resultados `evaluate` de cada algoritmo é retornado das funções `do_algoritmo`, como no exemplo da [linha 797](https://github.com/Model-R/Back-end/blob/master/ENM/fct/modelos.R#L797), que por acaso é do Bioclim, e que o nome da linha seria o nome da espécie.

Na função `do_bioclim` o avaluate é calculado na [linha 19](https://github.com/Model-R/Back-end/blob/master/ENM/fct/modelos.R#L19), com a função `evaluate`, **mas** a construção do arquivo a ser salvo como `evaluate` é feito a partir da [linha 21](https://github.com/Model-R/Back-end/blob/master/ENM/fct/modelos.R#L21) ), com a função `threshold`, seguindo com a inclusão de alguns outros parâmetros que são passados ao evaluate:
a. O threshold usado (linha 21)
b. A AUC, no campo de mesmo nome (linha 27);
c. TSS, campo de mesmo nome (L28);
d. Nome do algoritmo, campo de mesmo nome (L29);
e. Número da partição `partition` (L30);

Olhando a função `threshold` do pacote `dismo` e o seu guia de ajuda, ví que a função cria os campos 
`kappa`, `spec_sens`, `no_omission`, `prevalence`, `equal_sens_spec`, `sensitivity`. Logo, na linha 21, estaríamos calculando e salvando tais campos no objeto `evaluate`, adicionando outros nas linhas subsequentes.

Acho que com esse relato temos uma noção de como é calculado e cosntruido o referente objeto. Apesar de não responder sua pergunta:

> Uma coisa que estranhei é que a implementação antiga sempre escreve a 1ª coluna numérica igual à 2ª. Nesse exemplo 0.23519412. Isso faz sentido?

Ao rodar o exemplo reproduzível da função `threshold`, disponível no `help` do pacote `dismo` vi que   
o 1° (Kappa) resultado foi igual ao 2° (spec_sens):
```{r}
# this is a contrived example:
# p has the predicted values for 50 known cases (locations)
# with presence of the phenomenon (species)
p <- rnorm(50, mean=0.7, sd=0.3)
# b has the predicted values for 50 background locations (or absence)
a <- rnorm(50, mean=0.4, sd=0.4)
e <- evaluate(p=p, a=a)

threshold(e)

               kappa spec_sens no_omission prevalence equal_sens_spec sensitivity
thresholds 0.3497466 0.3497466 -0.06681487  0.4888647       0.5298743   0.3932349
```

Não sei se resolvi essa questão. Mas coloco outra: Se faz sentido o `Kappa` ser igual ao `spec_sens` por que na nova implementação isso não se manteve?

**Comment by AndreaSanchezTapia** [comment]
Pessoal, rapidamente
As medidas geradas por evaluate vêm da tabela de confusão, 
elas mudam com o threshold empregado para cortar os modelos contínuos em binários, 
então mudando o threshold dá para ter curvas, onde estes valores têm máximos e mínimos e inflexões. 
Isso ajuda a saber onde cortar.

O que evaluate faz é criar estas curvas calculando kappa e os demais para vários valores entre 0 e 1 
este corte é automático e não sei se é ajustável. 

O que kappa e spec_sens devolvem não é o valor mesmo de kappa e sepc_sens mas _o valor do threshold para o qual kappa e spec_sens se maximizam_. Como o intervalo para o qual eles foram calculados foi o mesmo, pode haver congruência nos valores sim.  

Por isso aparte de ter o threshold para TSS (spec_sens) eu faço o cálculo do TSS, porque evaluate não devolve esse valor.

**Comment by FelipeSBarros** [comment]
Então podemos entender que Kappa e spec_sens **podem** ter o mesmo valor. Mas que isso não é necessariamente uma regra.

Com relação à pergunta do @gmgall :
>Ambas as execuções foram feitas com o mesmo seed. Não deveriam ser exatamente iguais?
Ví no branch `Algoritmos_separados` que em `do_algoritmo` o seed é usado para a geração de pontos aleatórios e criação das partições (ex: linha 33)[https://github.com/Model-R/Back-end/blob/algoritmos_separados/ENM/fct/algoritmos/bioclim.R#L33};

Ou seja, o seed não tem sido usado nos algoritmos. Além disso, pelo pouco que conheço do Bioclim, não faz sentido eles terem valores diferentes pois tal algoritmos não possui nenhum elemento de aleatoriedade. Confirma, @AndreaSanchezTapia ?

**Comment by AndreaSanchezTapia** [comment]
Não sei por que surge a diferença mas acho que o que você diz é correto com relação a bioclim. Os modelos deveriam ser iguais (na minha cabeça). As diferenças podem surgir portanto da geração de ausências pois isso modificaria a tabela de confusão (mesmo que o modelo seja exatamente o mesmo). 

Mas não lembro mais se já falamos que a geração de ausência era exatamente igual ou se estas diferençass foram observadas ainda depois de corrigir isso.

Porém não acho que seja muito grave, podemos ir avançando e ficar com isso na mente.

**Comment by gmgall** [comment]
> Não sei se resolvi essa questão. Mas coloco outra: Se faz sentido o `Kappa` ser igual ao `spec_sens` por que na nova implementação isso não se manteve?

Exatamente o meu ponto com essa issue, @FelipeSBarros. Por que os resultados variam? Em que ponto inseri esse bug (se é um bug)?

Vocês chegaram a reproduzir o que relatei?

**Comment by gmgall** [comment]
Ok, colei os resultados lado a lado e o problema parece menor. A quantidade de campos é a mesma. Diferenças aparecem em `spec_sens`, `prevalence`, `AUC` e `TSS`.

```
kappa            0.23519412         0.23519412
spec_sens        0.23519412         0.11754706
no_omission      -1e-04             -1e-04
prevalence       0.35284118         -1e-04
equal_sens_spec  0.11754706         0.11754706
sensitivity      0.11754706         0.11754706
AUC              0.751633986928105  0.744510978043912
TSS              0.444444444444444  0.453759148369927
algoritmo        "BioClim"          "BioClim"
partition        1                  1
```

**Comment by AndreaSanchezTapia** [comment]
Desculpa Guilherme, vou perguntar de novo: 
1. A implementação é antiga com relação ao buffer, não é? Ou é modelos + buffer?
2. Quando vc está falando da implementação antiga vc está falando de uma rodada antiga ou você rodou a implementação antiga de novo (mantendo o seed entre ambas, suponho)? Como falei antes a única fonte de variação que penso é a geração de ausências que é aleatória e mudaria tudo. 

As diferenças são consequência uma da outra, (Tss é calculado a partir de spec_sens, por exemplo). Diferenças entre as AUC (e sobre tudo prevalências) indicam que são modelos diferentes, então algo mudou na rodada. Eu compararia
+ os sdm_data.txt, são os pontos de presença e ausência. Se os pontos de presença estão iguais e os de ausência mudaram isso responderia a pergunta e não tem consequências reais, basta manter como ficou agora. As figuras geradas em png (sdmdata) devem dar uma noção também. 

+ No entanto os valores tão diferentes de prevalência me fazem pensar que a diferença vem do buffer mesmo (será que antes estava com "mean" e agora com "max" ou viceversa?). Eu compararia os tif gerados (sobre tudo em termos de valores, plotando Values() de um em função do outro). De novo, se mudou não tem consequências reais mas ficaríamos sabendo o que foi.

Infelizmente não pude checar até hoje mas eu iria direto nessas duas comparações.

**Comment by gmgall** [comment]
> 1. A implementação é antiga com relação ao buffer, não é? Ou é modelos + buffer?
> 2. Quando vc está falando da implementação antiga vc está falando de uma rodada antiga ou você rodou a implementação antiga de novo (mantendo o seed entre ambas, suponho)? Como falei antes a única fonte de variação que penso é a geração de ausências que é aleatória e mudaria tudo.

Fui confuso com isso, foi mal.

* implementação nova = último commit de `master`, minhas funções em `ENM/fct/algoritmos` ou a `dismo.mod()` (não apaguei `modelos.R` apesar de ter reimplementado tudo em `ENM/fct/algoritmos`)
* implementação antiga = `dismo.mod()` na **tag [coordenador-IIS](https://github.com/Model-R/Back-end/releases/tag/coordenador-IIS)**, que marca o último commit que fizemos no repositório antigo: coordenador-IIS/ARF_spatial_planning@7a79bbd994049796ef1ca0d4c8e897ce9d99d763

**O mesmo seed foi usado (512) e o teste foi feito sem buffer.**

> os sdm_data.txt, são os pontos de presença e ausência. Se os pontos de presença estão iguais e os de ausência mudaram isso responderia a pergunta e não tem consequências reais, basta manter como ficou agora. As figuras geradas em png (sdmdata) devem dar uma noção também.

Um diff entre o `sdm_data.txt` da implementação nova e o da implementação antiga mostra que são diferentes. Se quiser, posso fornecer a saída para vocês.

**Comment by AndreaSanchezTapia** [comment]
seria ótimo. ou postar no slack os arquivos mesmo. se ainda os arquivos que terminam em dataset.png são gerados também seria ótimo vê-los, por favor :)
(aqueles gerados pelo comando `png(filename=paste0(models.dir,"/",sp,"/",i,sp,"dataset.png"))`)

**Comment by gmgall** [comment]
Coloquei os arquivos em 2 gists:

* [implementação antiga](https://gist.github.com/gmgall/211548363280eea1a2ea3a1b8ebf1bf9)
* [implementação nova](https://gist.github.com/gmgall/b272c6e89bf047844599a44f11ac3d4c)

No processo de fazê-los, talvez tenha matado a charada: a implementação antiga ignorava o parâmetro `n.back`; a nova, o leva em consideração. Isso foi corrigido em #4 (e eu tinha esquecido completamente, ainda bem que está documentado).

O `sdmdata.txt` da implementação antiga tem o que parecem ser 52 pontos de ausência e 26 de presença. Exatamente o que foi mudado em #4. O da implementação nova tem 500 pontos de ausência (o valor que passei para `n.back`) e os mesmos 26 pontos no início do arquivo, que estou assumindo serem os de presença.

Isso justifica as diferenças de valores entre a implementação nova vs a antiga?

**Comment by AndreaSanchezTapia** [comment]
Justifica plenamente.
Os evaluate são os mesmos que vc mostrou antes?

**Comment by gmgall** [comment]
Adicionei os arquivos `evaluate*` nos gists, se quiser dar uma olhada:

* [implementação antiga](https://gist.github.com/gmgall/211548363280eea1a2ea3a1b8ebf1bf9)
* [implementação nova](https://gist.github.com/gmgall/b272c6e89bf047844599a44f11ac3d4c)

Mas sim, os valores dessa rodada de testes parecem iguais aos que informei na mensagem que abre essa issue. Exemplo:

Implementação antiga:
```
"Zygia latifolia (L.) Fawc. & Rendle 1 BioClim" 0.23519412 0.23519412 -1e-04 0.35284118 0.11754706 0.11754706 0.751633986928105 0.444444444444444 "BioClim" 1
```

Implementação nova:
```
"Zygia latifolia (L.) Fawc. & Rendle 1 BioClim" 0.23519412 0.11754706 -1e-04 -1e-04 0.11754706 0.11754706 0.744510978043912 0.453759148369927 "BioClim" 1
```

**Comment by AndreaSanchezTapia** [comment]
A única coisa que chama minha atenção é as prevalências serem tão diferentes (4 ordens de magnitude) com modelos finais quase iguais. Talvez a prevalência seja calculada a partir dos pontos e não dos modelos, o qual explicaria a diferença. Nesse caso as prevalências para todos os algoritmos deveriam ser iguais, você poderia checar isso já para terminar? Obrigada

**Comment by gmgall** [comment]
Os arquivos `evaluate*` estão nos gists que listei acima, se quiser dar uma olhada também.

----------------

Usando o `cut` do Unix para imprimir o 4º campo (que estou assumindo ser prevalência), o nome do algoritmo e a partição, temos o seguinte para a **implementação antiga**:

```
$ cut -f12,17,18 -d' ' evaluateZygia\ latifolia\ \(L.\)\ Fawc.\ \&\ Rendle_* | column -t

0.35284118   "BioClim"  1
0.33223627   "Domain"   1
0.35780849   "maxent"   1
-0.09547024  "Mahal"    1
0.36394223   "glm"      1
0.34053333   "rf"       1
0.29923205   "svm"      1
0.31513123   "svm2"     1

0.33323333   "BioClim"  2
0.3673829    "Domain"   2
0.27717804   "maxent"   2
0.05808274   "Mahal"    2
0.33966253   "glm"      2
0.36126667   "rf"       2
0.30632694   "svm"      2
0.28003405   "svm2"     2

0.23539412   "BioClim"  3
0.37522378   "Domain"   3
0.31727772   "maxent"   3
0.39695456   "Mahal"    3
0.32087437   "glm"      3
0.3324       "rf"       3
0.35033727   "svm"      3
0.3338706    "svm2"     3
```

E para a **implementação nova**:

```
$ cut -f12,17,18 -d' ' evaluateZygia\ latifolia\ \(L.\)\ Fawc.\ \&\ Rendle_* | column -t

-1e-04       "BioClim"  1
0.05012835   "Domain"   1
0.04926751   "glm"      1
-0.09547024  "Mahal"    1
0.05138817   "maxent"   1
0.0482       "rf"       1
0.04110035   "svm2"     1
0.03818738   "svm"      1

-1e-04       "BioClim"  2
0.05165712   "Domain"   2
0.04941135   "glm"      2
0.05808274   "Mahal"    2
0.0457659    "maxent"   2
0.0504       "rf"       2
0.05101663   "svm2"     2
0.04687261   "svm"      2

-1e-04       "BioClim"  3
0.06156125   "Domain"   3
0.05073029   "glm"      3
0.02977248   "Mahal"    3
0.05086973   "maxent"   3
0.0495       "rf"       3
0.04939472   "svm2"     3
0.05116141   "svm"      3
```

Obs: os `cut` acima listam o 12º, 17º e 18º campos porque informei como separador de campos o espaço (`-d' '`).

Faz sentido os valores acima?

Vários deles são **próximos** para um mesmo algoritmo/implementação. Exemplo: Bioclim tem 0.35284118, 0.33323333 e 0.23539412 nas 3 partições (implementação antiga). Na implementação nova é -1e-04 para todas as partições.

Já o Domain tem 0.33223627,  0.3673829 e 0.37522378 nas 3 partições na implementação antiga; e  0.05012835, 0.05165712 e 0.06156125 na implementação nova.

Não sei se entendi direito o que você perguntou, mas os dados estão aí. Avise-me se eu puder ajudar com mais algum tipo de filtragem/transformação desses dados.

**Comment by FelipeSBarros** [comment]
Pessoal ( @gmgall e @AndreaSanchezTapia ), conforme combinado reví essa issue.

O segundo a leitura dos comentários, essa issue foi criada pois houve uma diferença entre os resultados obtidos pela "implementação" [antiga](https://gist.github.com/gmgall/211548363280eea1a2ea3a1b8ebf1bf9) das funções (tag: [**Coordenador-IIS**](https://github.com/Model-R/Back-end/releases/tag/coordenador-IIS)) e uma [versão mais recente](https://gist.github.com/gmgall/b272c6e89bf047844599a44f11ac3d4c).

Segundo o [comentário](https://github.com/Model-R/Back-end/issues/6#issuecomment-302247558) do @gmgall o "problema" que originou essa issue (a diferença entre os resultados) foi originado com a resolução da issue #4 ("Parametro dismo.mod sem efeito").

Ou seja, é esperado que as implementações comparadas sejam diferentes, uma vez que possuem origem no uso do buffer para a criação das pseudo ausências.

O problem é que a conversa foi descontinuada. Mas acredito que **essa issue possa ser fechada**.

**Comment by gmgall** [comment]
Pelo que me recordo, foi isso mesmo. Acho que está tudo certo.

Fecharei e se for o caso reabrimos, ok?
