### ISSUE TITLE
Criar pacote Model-R

### ISSUE THREAD

**Issue by gmgall** [Model-R/Back-end#8]
Criar um pacote R com os algoritmos implementados.

Isso resolve o problema com paths relativos.

**Comment by gmgall** [comment]
Estive trabalhando nisso nos últimos dias e cheguei num pacote quase totalmente funcional. Ele está no repositório [modelr_pkg](https://github.com/Model-R/modelr_pkg). Não fiz um commit aqui mesmo porque seria uma mudança muito radical na estrutura dos arquivos. Quando estiver tudo OK com o pacote, faço um mega commit aqui explicando cada mudança.

De fato resolve-se o problema dos paths relativos. :fireworks: 

O pacote `modelr` pode ser carregado assim:

1) No shell faça

```shell
git clone https://github.com/Model-R/modelr_pkg.git
```

2) e no R

```R
devtools::load_all("modelr_pkg")
```

Ele também pode ser **instalado** numa *library*:

```R
devtools::install_github("Model-R/modelr_pkg")
```

**Não recomendo instalá-lo por enquanto** porque ainda tem coisa pra resolver; mas se testarem, verão que as dependências todas serão instaladas antes. :smiley: 

--------------------

Informo agora o que deu certo e o que deu errado para vocês me ajudarem.

1) As funções de modelagem `do_*` funcionaram todas. A única coisa que precisei remover delas é a geração de PNGs. Mantendo o trecho de código que gera os PNGs recebo o seguinte erro:

```
Error in as.double(y) : 
  cannot coerce type 'S4' to vector of type 'double'
```

Entendo a geração de PNGs e a modelagem como processos distintos, então poderíamos criar uma função separada para isso caso não consigamos resolver esse problema. De uma forma ou de outra, precisamos saber porque isso passou a ocorrer *só dentro do pacote*.

2)  `finalModel()` gera o seguinte erro quando seleciono todos os algoritmos:

```R
> finalModel("Zygia latifolia (L.) Fawc. & Rendle", algoritmos = c("maxent", "rf", "svm", "BioClim", "glm", "svm2", "Domain", "Mahal"), models.dir="/tmp/novo2")

[1] "Fri Sep  8 17:44:38 2017"
Zygia latifolia (L.) Fawc. & Rendle 
Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle maxent 
1 partition was selected for Zygia latifolia (L.) Fawc. & Rendle maxent 
select Zygia latifolia (L.) Fawc. & Rendle maxent DONE 
Extracting data for rf 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle rf 
3 partitions were selected for Zygia latifolia (L.) Fawc. & Rendle 
Error in if (drop) { : argumento não é interpretável como lógico
Além disso: Warning messages:
1: In mean.default(cont.sel) :
  argument is not numeric or logical: returning NA
2: In mean.default(bin.sel) :
  argument is not numeric or logical: returning NA
```

Se eu removo o algoritmo Random Forest, a execução chega até o fim:

```R
finalModel("Zygia latifolia (L.) Fawc. & Rendle", algoritmos = c("maxent", "svm", "BioClim", "glm", "svm2", "Domain", "Mahal"), models.dir="/tmp/novo2")
[1] "Sat Sep  9 20:23:41 2017"
Zygia latifolia (L.) Fawc. & Rendle 
Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle maxent 
1 partition was selected for Zygia latifolia (L.) Fawc. & Rendle maxent 
select Zygia latifolia (L.) Fawc. & Rendle maxent DONE 
Extracting data for svm 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle svm 
No partition was selected for Zygia latifolia (L.) Fawc. & Rendle svm 
select Zygia latifolia (L.) Fawc. & Rendle svm DONE 
Extracting data for BioClim 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle BioClim 
No partition was selected for Zygia latifolia (L.) Fawc. & Rendle BioClim 
select Zygia latifolia (L.) Fawc. & Rendle BioClim DONE 
Extracting data for glm 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle glm 
No partition was selected for Zygia latifolia (L.) Fawc. & Rendle glm 
select Zygia latifolia (L.) Fawc. & Rendle glm DONE 
Extracting data for svm2 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle svm2 
1 partition was selected for Zygia latifolia (L.) Fawc. & Rendle svm2 
select Zygia latifolia (L.) Fawc. & Rendle svm2 DONE 
Extracting data for Domain 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle Domain 
No partition was selected for Zygia latifolia (L.) Fawc. & Rendle Domain 
select Zygia latifolia (L.) Fawc. & Rendle Domain DONE 
Extracting data for Mahal 
Reading models from .tif files 
selecting partitions for Zygia latifolia (L.) Fawc. & Rendle Mahal 
1 partition was selected for Zygia latifolia (L.) Fawc. & Rendle Mahal 
select Zygia latifolia (L.) Fawc. & Rendle Mahal DONE 
[1] "DONE Mahal \n"
[1] "Sat Sep  9 20:23:47 2017"
[1] "Sat Sep  9 20:23:47 2017"
```

:warning: **Percebam que todos os algoritmos que funcionaram tiveram 1 ou 0 partições selecionadas. O Random Forest teve 3.** Talvez não tenha nada a ver com o algoritmo e sim com o que [acontece após a verificação da linha 74 em `final_model.R`](https://github.com/Model-R/Back-end/blob/0a1feeaf256372d6f8339c5267d4a64ed48481f8/ENM/fct/final_model.R#L74)

3) `ensemble()` termina com o seguinte erro

```R
ensemble("Zygia latifolia (L.) Fawc. & Rendle", models.dir="/tmp/novo2", occs=coordenadas)
Final.bin.mean3 - Zygia latifolia (L.) Fawc. & Rendle 
7 models to ensemble from for Zygia latifolia (L.) Fawc. & Rendle 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘writeRaster’ for signature ‘"numeric", "character"’
Além disso: Warning message:
In mean.default(mod2) : argument is not numeric or logical: returning NA
```

OBS: `ensemble()` ainda recebe ocorrências de outras espécies além da de interesse e as filtra depois (vide [linha 38](https://github.com/Model-R/Back-end/blob/0a1feeaf256372d6f8339c5267d4a64ed48481f8/ENM/fct/ensemble.R#L38)). Precisamos mudar isso, assim como foi feito nas funções de modelagem.

**Comment by AndreaSanchezTapia** [comment]
@gmgall , acho que isso tem a ver com o fato de que a escritura das tabelas "evaluate" mudou. 

>  Não sei se a tabela ficou com uma coluna algoritmo, que indique o algoritmo a ser retido (`stats$algoritmo`) e isso provavelmente afeta a criação de `sel.index`e `stats2`. 

não é isso porque o objeto `sel.index` existe. (e o length é 3 nos casos que dá erro)

Quando `length(sel.index ) == 1` só os modelos bin são usados. Pode ser na leitura dos modelos "cont" que está o erro. O nome dos arquivos segue o mesmo padrão?

**Comment by AndreaSanchezTapia** [comment]
> OBS: ensemble() ainda recebe ocorrências de outras espécies além da de interesse e as filtra depois (vide linha 38). Precisamos mudar isso, assim como foi feito nas funções de modelagem.

O engraçado é que isso é apenas para que na hora de plotar, os pontos da espécie apareçam. O ensemble em si não precisa para nada.

**Comment by gmgall** [comment]
Não mudei o padrão de nome dos arquivos para criar o pacote.

Exemplo do diretório onde estão os arquivos de saída:

```shell
$ ls -1 BioClim*
BioClim_bin_Zygia latifolia (L.) Fawc. & Rendle_1.tif
BioClim_bin_Zygia latifolia (L.) Fawc. & Rendle_2.tif
BioClim_bin_Zygia latifolia (L.) Fawc. & Rendle_3.tif
BioClim_cont_Zygia latifolia (L.) Fawc. & Rendle_1.tif
BioClim_cont_Zygia latifolia (L.) Fawc. & Rendle_2.tif
BioClim_cont_Zygia latifolia (L.) Fawc. & Rendle_3.tif
BioClim_cut_Zygia latifolia (L.) Fawc. & Rendle_1.tif
BioClim_cut_Zygia latifolia (L.) Fawc. & Rendle_2.tif
BioClim_cut_Zygia latifolia (L.) Fawc. & Rendle_3.tif
```

Vê algum problema, @AndreaSanchezTapia?

**Comment by diogosbr** [comment]
Em:
2. finalModel() gera o seguinte erro quando seleciono todos os algoritmos:
Acho que o erro é dado porque na hora do extract, os pontos estão fora do raster ambiental e aí gera NA e o randomforest não lida bem com os NAs.

**Comment by AndreaSanchezTapia** [comment]
@gmgall a princípio não mas vou ter que ver aqui. Queria saber se tem a ver com como ficou escrita a tabela evaluate. 

@diogosbr mas final model não faz extract... tem que ser outra coisa porque é na fase de juntar os modelos que foram criados.

**Comment by gmgall** [comment]
Random Forest gera os seguintes warnings durante a modelagem

```
Warning messages:
1: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
2: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
3: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
```

Isso já acontecia antes do "empacotamento", então não achei relevante informar na minha mensagem original. Tem a ver com o que você sugeriu, @diogosbr?

Se tiver, informem-me uma espécie em que isso não ocorra para eu testar aqui.

----------------

Os `evaluate` ficaram assim, @AndreaSanchezTapia :

```
$ cat evaluateZygia\ latifolia\ \(L.\)\ Fawc.\ \&\ Rendle_1_randomforest.txt 
"kappa" "spec_sens" "no_omission" "prevalence" "equal_sens_spec" "sensitivity" "AUC" "TSS" "algoritmo" "partition"
"Zygia latifolia (L.) Fawc. & Rendle 1 rf" 0.25213333 0.09366667 0.00416667 0.0492 0.09366667 0.00426667 0.879948914431673 0.745210727969349 "rf" 1

$ cat evaluateZygia\ latifolia\ \(L.\)\ Fawc.\ \&\ Rendle_2_randomforest.txt 
"kappa" "spec_sens" "no_omission" "prevalence" "equal_sens_spec" "sensitivity" "AUC" "TSS" "algoritmo" "partition"
"Zygia latifolia (L.) Fawc. & Rendle 2 rf" 0.22046667 0.0651 0.02013333 0.05046667 0.0651 0.02213333 0.92156862745098 0.711601307189543 "rf" 2

$ cat evaluateZygia\ latifolia\ \(L.\)\ Fawc.\ \&\ Rendle_3_randomforest.txt 
"kappa" "spec_sens" "no_omission" "prevalence" "equal_sens_spec" "sensitivity" "AUC" "TSS" "algoritmo" "partition"
"Zygia latifolia (L.) Fawc. & Rendle 3 rf" 0.21346667 0.14023333 0.00843333 0.04926667 0.0652 0.0087 0.894669235709698 0.714193962748876 "rf" 3
```

Listei só os do Random Forest. Informem-me se quiserem ver todos.

**Comment by AndreaSanchezTapia** [comment]
clonei o branch. copiei e colei uma pasta aleatória de uma espécie do benchmark. no caso 

Actinostemon concolor (Spreng.) Müll.Arg.

então 
```
sp <- list.files("./models")
finalModel(sp, final.dir = "testsetembro")
[1] "Mon Sep 11 14:18:42 2017"
Actinostemon concolor (Spreng.) Müll.Arg. 
Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Actinostemon concolor (Spreng.) Müll.Arg. maxent 
2 partitions were selected for Actinostemon concolor (Spreng.) Müll.Arg. 
select Actinostemon concolor (Spreng.) Müll.Arg. maxent DONE 

Extracting data for rf 
Reading models from .tif files 
selecting partitions for Actinostemon concolor (Spreng.) Müll.Arg. rf 
2 partitions were selected for Actinostemon concolor (Spreng.) Müll.Arg. 
select Actinostemon concolor (Spreng.) Müll.Arg. rf DONE 
Extracting data for svm 
Reading models from .tif files 
selecting partitions for Actinostemon concolor (Spreng.) Müll.Arg. svm 
3 partitions were selected for Actinostemon concolor (Spreng.) Müll.Arg. 
select Actinostemon concolor (Spreng.) Müll.Arg. svm DONE 
[1] "DONE svm \n"
[1] "Mon Sep 11 14:18:45 2017"
[1] "Mon Sep 11 14:18:45 2017"
```

a pasta resultante tem tudo tranquilo. Será que é alguma coisa relacionada com as pastas @gmgall ?

**Comment by AndreaSanchezTapia** [comment]
> Random Forest gera os seguintes warnings durante a modelagem

Warning messages:
1: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
2: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
3: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?

Isso já acontecia antes do "empacotamento", então não achei relevante informar na minha mensagem original. Tem a ver com o que você sugeriu, @diogosbr?

Esse warning() é tecnicamente verdade, mas ele não impede a modelagem e pelo que vejo os modelos ficaram com TSS de 0.7 então esse não deveria ser o problema. 

Tente com a espécie que eu fiz Guilherme. ^shrugs^

**Comment by gmgall** [comment]
Testando com `Actinostemon concolor (Spreng.) Müll.Arg.` temos o seguinte warning com maxent:

```
Warning messages:
1: In .local(x, p, ...) :
  2 (1.01%) of the presence points have NA predictor values
2: In .local(x, p, ...) :
  2 (1.01%) of the presence points have NA predictor values
3: In .local(x, p, ...) :
  2 (1.01%) of the presence points have NA predictor values
```

Com Random Forest, o seguinte erro:

```
Actinostemon concolor (Spreng.) Müll.Arg. partition number 1 
Error in na.fail.default(list(`sdmdata_train$pa` = c(1, 1, 1, 1, 1, 1,  : 
  missing values in object
Calls: do_randomForest ... model.frame.default -> <Anonymous> -> na.fail.default
Execução interrompida
```

Com GLM, o seguinte erro:

```
GLM 
Actinostemon concolor (Spreng.) Müll.Arg. partition number 1 
Error in step(object = null.model, scope = formula(full.model), direction = "both",  : 
  number of rows in use has changed: remove missing values?
Calls: do_GLM -> step
Além disso: Warning message:
In add1.glm(fit, scope$add, scale = scale, trace = trace, k = k,  :
  using the 527/529 rows from a combined fit
Execução interrompida
```

Com SVM2, o seguinte warning:

```
Warning messages:
1: In pred - true.y :
  comprimento do objeto maior não é múltiplo do comprimento do objeto menor
2: In pred - true.y :
  comprimento do objeto maior não é múltiplo do comprimento do objeto menor
3: In pred - true.y :
  comprimento do objeto maior não é múltiplo do comprimento do objeto menor
4: In pred - true.y :
  comprimento do objeto maior não é múltiplo do comprimento do objeto menor
5: In pred - true.y :
  comprimento do objeto maior não é múltiplo do comprimento do objeto menor
```

Resumindo:

* OK: Domain, Bioclim, Mahalanobis, SVM :white_check_mark: 
* Terminam com warning: Maxent, SVM2 :warning: 
* Dão erro: Random Forest, GLM :x: 

-----------------------

Testando `finalModel()` com **todos os algoritmos**:

```R
finalModel(especie, algoritmos=c("maxent", "rf", "svm", "BioClim", "glm", "svm2", "Domain", "Mahal"), models.dir="/tmp/novo3")
[1] "Mon Sep 11 15:30:51 2017"
Actinostemon concolor (Spreng.) Müll.Arg. 
Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Actinostemon concolor (Spreng.) Müll.Arg. maxent 
3 partitions were selected for Actinostemon concolor (Spreng.) Müll.Arg. 
Error in if (drop) { : argumento não é interpretável como lógico
Além disso: Warning messages:
1: In mean.default(cont.sel) :
  argument is not numeric or logical: returning NA
2: In mean.default(bin.sel) :
  argument is not numeric or logical: returning NA
```

Testando `finalModel()` com **algoritmos *default***:

```R
finalModel(especie, models.dir="/tmp/novo3")
[1] "Mon Sep 11 15:33:44 2017"
Actinostemon concolor (Spreng.) Müll.Arg. 
Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Actinostemon concolor (Spreng.) Müll.Arg. maxent 
3 partitions were selected for Actinostemon concolor (Spreng.) Müll.Arg. 
Error in if (drop) { : argumento não é interpretável como lógico
Além disso: Warning messages:
1: In mean.default(cont.sel) :
  argument is not numeric or logical: returning NA
2: In mean.default(bin.sel) :
  argument is not numeric or logical: returning NA
```

**Comment by diogosbr** [comment]
@AndreaSanchezTapia , não acho que o erro seja nos warnings(), pois como vc dissse, eles não impedem de gerar os modelos. 

@gmgall , Acho que é o mesmo problema de  ter dados  com NA, pelo menos em RF. Talvez o problema do GLM seja o mesmo. 
Já os warnings do maxent são normais...rsrs
Precisamos realmente ter um conjunto de dados limpos (como Andrea comentou). Vou providenciar um conjunto de dados essa semana. É que to meio atolado com a submissão de um projeto com a Marinez nesses dias. 

Em algum momento no script (ou no shiny) tem uma rotina para retirar os pontos que geram NA. Mas, se quiser testar logo, tenho uma função que faz isso, mas ela retorna uma tabela apenas com duas colunas (lat e long), não sei até que ponto isso vai ajudar.

**Comment by gmgall** [comment]
Ou seja: na opinião de vocês tudo está funcionando como sempre funcionou antes, os dados de entrada que não estão "limpos"?

Por que não me recordo desses problemas antes ao testar com a `Zygia latifolia (L.) Fawc. & Rendle`. Posso estar enganado, claro. Passei muito mais tempo mexendo nas funções `do_*` do que em `finalModel()` e `ensemble()`.

De qualquer forma, fico no aguardo desses dados "limpos" para testar então.

**Comment by AndreaSanchezTapia** [comment]
Não, o que acho é que para saber isso precisamos do "exemplo limpo". Até a modelagem feita pro benchmark estava tudo funcionando, mas as funções podem não ter acompanhado mudanças recentes. Se desse para fazer uma rodada de modelagem e aparte testar `finalModel()` e `ensemble()` seria ótimo, mas todos os erros que você está encontrando ainda são na fase de modelagem.

**Comment by diogosbr** [comment]
Coloquei na pasta 'data' uma tabela chamada dados_clean.csv com registros de algumas espécie e que nao geram NA.

**Comment by gmgall** [comment]
Terminei o 1º teste com os dados de `dados_clean.csv`.

A execução das funções `do_*` foram sem problemas. :white_check_mark: 

A `finalModel()` **do pacote** deu o mesmo erro:

```R
> finalModel(especie, algoritmos=c("maxent", "rf", "svm", "BioClim", "glm", "svm2", "Domain", "Mahal"), models.dir="/tmp/novo", TSS.value = 0.5)
[1] "Wed Sep 13 12:58:50 2017"
Eugenia florida DC. 
Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. maxent 
3 partitions were selected for Eugenia florida DC. 
Error in if (drop) { : argumento não é interpretável como lógico
Além disso: Warning messages:
1: In mean.default(cont.sel) :
  argument is not numeric or logical: returning NA
2: In mean.default(bin.sel) :
  argument is not numeric or logical: returning NA
```

Carreguei a **original** desse repositório e a execução foi até o final :white_check_mark: 

```
> source("~/repos/ARF_spatial_planning/ENM/fct/final_model.R")
> ?finalModel
Using development documentation for finalModel
> finalModel(especie, algoritmos=c("maxent", "rf", "svm", "BioClim", "glm", "svm2", "Domain", "Mahal"), models.dir="/tmp/novo")
[1] "Wed Sep 13 12:59:47 2017"
Eugenia florida DC. 
Loading required package: sp
data.table 1.10.0
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com

Attaching package: ‘data.table’

The following object is masked from ‘package:raster’:

    shift

Reading the evaluation files 
Extracting data for maxent 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. maxent 
3 partitions were selected for Eugenia florida DC. 
select Eugenia florida DC. maxent DONE 
Extracting data for rf 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. rf 
3 partitions were selected for Eugenia florida DC. 
select Eugenia florida DC. rf DONE 
Extracting data for svm 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. svm 
3 partitions were selected for Eugenia florida DC. 
select Eugenia florida DC. svm DONE 
Extracting data for BioClim 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. BioClim 
No partition was selected for Eugenia florida DC. BioClim 
select Eugenia florida DC. BioClim DONE 
Extracting data for glm 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. glm 
No partition was selected for Eugenia florida DC. glm 
select Eugenia florida DC. glm DONE 
Extracting data for svm2 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. svm2 
3 partitions were selected for Eugenia florida DC. 
select Eugenia florida DC. svm2 DONE 
Extracting data for Domain 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. Domain 
No partition was selected for Eugenia florida DC. Domain 
select Eugenia florida DC. Domain DONE 
Extracting data for Mahal 
Reading models from .tif files 
selecting partitions for Eugenia florida DC. Mahal 
3 partitions were selected for Eugenia florida DC. 
select Eugenia florida DC. Mahal DONE 
[1] "DONE Mahal \n"
[1] "Wed Sep 13 12:59:56 2017"
[1] "Wed Sep 13 12:59:56 2017"
```

Os avisos do início da execução que me chamaram a atenção. O pacote `data.table` precisa estar *attached* para a função funcionar.

Ele já está listado como dependência do pacote. Preciso descobrir a melhor maneira de fazer isso no contexto de um pacote. Estarei estudando isso nas próximas horas.

**Comment by AndreaSanchezTapia** [comment]
Pois é, a única diferença é a chamada explícita aos pacotes, por que não botar de novo as linhas `library()`? Se for dependência isso não significa que carregue ele...

**Comment by gmgall** [comment]
`library()` e `require()` causam efeitos colaterais indesejados quando usados num pacote.

Leia sobre isso [desse ponto do livro do Wickham](http://r-pkgs.had.co.nz/r.html#r-differences) até o final do capítulo.

**Comment by AndreaSanchezTapia** [comment]
É relacionado com isto então, suponho http://r-pkgs.had.co.nz/namespace.html

**Comment by gmgall** [comment]
Sim.

Do capítulo que você citou (grifo meu):

> Listing a package in either Depends or Imports ensures that it’s installed when needed. The main difference is that where Imports just loads the package, Depends attaches it. There are no other differences. The rest of the advice in this chapter applies whether or not the package is in Depends or Imports.
>
> **Unless there is a good reason otherwise, you should always list packages in Imports not Depends. That’s because a good package is self-contained, and minimises changes to the global environment (including the search path).**

**Comment by gmgall** [comment]
Finalmente consegui resolver. :smiley: Temos um pacote que funcionou redondo `do_*()` + `finalModel()` + `ensemble()` com as espécies que o @diogosbr forneceu em `dados_clean.csv`. Fiz o commit em [Model-R/modelr_pkg](https://github.com/Model-R/modelr_pkg).

Testem se tiverem oportunidade, por favor.

Para facilitar, já deixo um [script pronto que testa todas as funções do pacote](https://gist.github.com/gmgall/1b240bcfe96022b6ed2f10470a710deb). Só é necessário ajustar os _paths_ para o sistema de vocês.

O raciocínio todo para resolução do problema foi bem longo. Documento aqui depois.

**Comment by FelipeSBarros** [comment]
@gmgall , parabens!
Tentei rodar com o seu script, mas tive erro pelo `maxent`...
```
Maxent 
Eugenia florida DC. partition number 1 
 Show Traceback
 
 Rerun with Debug
 Error in .getMeVersion() : file missing:
/home/felipe/R/x86_64-pc-linux-gnu-library/3.4/dismo/java/maxent.jar.
Please download it here: http://www.cs.princeton.edu/~schapire/maxent/ 
```
Não lembro se havíamos incluido a "instalação" do maxent em nossos procedimentos.
De qq forma, fiz o download e colcoquei na pasta solicitada e tudo está correndo bem!

**Comment by FelipeSBarros** [comment]
Rodou tudo bem e os resultados parecem Ok. Ou seja, tudo conforme o esperado: evaluate criado, raster de cada partição, final e ensemble.
De warnings, tive:
```
There were 27 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
2: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
3: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
4: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
5: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
6: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
7: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
8: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
9: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
10: glm.fit: fitted probabilities numerically 0 or 1 occurred
11: glm.fit: fitted probabilities numerically 0 or 1 occurred
12: glm.fit: fitted probabilities numerically 0 or 1 occurred
13: glm.fit: fitted probabilities numerically 0 or 1 occurred
14: glm.fit: fitted probabilities numerically 0 or 1 occurred
15: glm.fit: fitted probabilities numerically 0 or 1 occurred
16: glm.fit: fitted probabilities numerically 0 or 1 occurred
17: glm.fit: fitted probabilities numerically 0 or 1 occurred
18: glm.fit: fitted probabilities numerically 0 or 1 occurred
19: glm.fit: fitted probabilities numerically 0 or 1 occurred
20: glm.fit: fitted probabilities numerically 0 or 1 occurred
21: glm.fit: fitted probabilities numerically 0 or 1 occurred
22: glm.fit: fitted probabilities numerically 0 or 1 occurred
23: glm.fit: fitted probabilities numerically 0 or 1 occurred
24: glm.fit: fitted probabilities numerically 0 or 1 occurred
25: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
26: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
27: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression```

Com relação aos `warnings` do RandomForest, lembro de serem isso mesmo pois ele tem a possibilidade de fazer uma "classificação" ao invés da "regressão".
Do glm, desconheço, mas os dados foram criados corretamente...

**Comment by gmgall** [comment]
Eu recebi esses warnings também. Os do Random Forest lembro que com certeza ocorriam fora do pacote também.

Os do GLM que não reconheço.

Estou assumindo que está tudo certo.

**Comment by AndreaSanchezTapia** [comment]
vou fechar esta issue, gente.
